name: Deploy the backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check the code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: devanshbehl/todo-app-backend:${{ github.sha }}
      
      - name: Deploy to DigitalOcean
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh \
            -o StrictHostKeyChecking=no \
            -i ~/ssh_key \
            root@143.110.250.238 \
            "
              docker pull devanshbehl/todo-app-backend:${{ github.sha }}

              docker stop user_backend || true
              docker rm user_backend || true

              docker run -d \
                --name user_backend \
                -p 3001:3001 \
                --env-file /root/.env \
                devanshbehl/todo-app-backend:${{ github.sha }}
            "